# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


import photo_rc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AutoMail(object):
    def setupUi(self, AutoMail):
        AutoMail.setObjectName("AutoMail")
        AutoMail.resize(800, 610)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        AutoMail.setFont(font)
        AutoMail.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        AutoMail.setTabShape(QtWidgets.QTabWidget.Rounded)
        AutoMail.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(AutoMail)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 800, 511))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setToolTip("")
        self.tabWidget.setStatusTip("")
        self.tabWidget.setWhatsThis("")
        self.tabWidget.setAccessibleName("")
        self.tabWidget.setAccessibleDescription("")
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setLocale(QtCore.QLocale(
            QtCore.QLocale.English, QtCore.QLocale.India))
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.Open = QtWidgets.QWidget()
        self.Open.setObjectName("Open")
        self.openCsv = QtWidgets.QLabel(self.Open)
        self.openCsv.setGeometry(QtCore.QRect(30, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.openCsv.setFont(font)
        self.openCsv.setObjectName("openCsv")
        self.csvPath = QtWidgets.QLineEdit(self.Open)
        self.csvPath.setGeometry(QtCore.QRect(150, 20, 451, 41))
        self.csvPath.setObjectName("csvPath")
        self.browse = QtWidgets.QPushButton(self.Open)
        self.browse.setGeometry(QtCore.QRect(620, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.browse.setFont(font)
        self.browse.setObjectName("browse")
        self.name = QtWidgets.QLabel(self.Open)
        self.name.setGeometry(QtCore.QRect(30, 90, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.nameCol = QtWidgets.QComboBox(self.Open)
        self.nameCol.setGeometry(QtCore.QRect(150, 90, 141, 31))
        self.nameCol.setObjectName("nameCol")
        self.mail = QtWidgets.QLabel(self.Open)
        self.mail.setGeometry(QtCore.QRect(320, 90, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.mail.setFont(font)
        self.mail.setObjectName("mail")
        self.mailCol = QtWidgets.QComboBox(self.Open)
        self.mailCol.setGeometry(QtCore.QRect(440, 90, 151, 31))
        self.mailCol.setObjectName("mailCol")
        self.openCer = QtWidgets.QLabel(self.Open)
        self.openCer.setGeometry(QtCore.QRect(30, 150, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.openCer.setFont(font)
        self.openCer.setObjectName("openCer")
        self.cerPath = QtWidgets.QLineEdit(self.Open)
        self.cerPath.setGeometry(QtCore.QRect(150, 150, 451, 41))
        self.cerPath.setObjectName("cerPath")
        self.browse_2 = QtWidgets.QPushButton(self.Open)
        self.browse_2.setGeometry(QtCore.QRect(620, 150, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.browse_2.setFont(font)
        self.browse_2.setObjectName("browse_2")
        self.line = QtWidgets.QFrame(self.Open)
        self.line.setGeometry(QtCore.QRect(10, 210, 771, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.loadData = QtWidgets.QPushButton(self.Open)
        self.loadData.setGeometry(QtCore.QRect(620, 80, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.loadData.setFont(font)
        self.loadData.setObjectName("loadData")
        self.showData = QtWidgets.QTextBrowser(self.Open)
        self.showData.setGeometry(QtCore.QRect(20, 230, 301, 241))
        self.showData.setObjectName("showData")
        self.showCer = QtWidgets.QLabel(self.Open)
        self.showCer.setGeometry(QtCore.QRect(340, 230, 441, 241))
        self.showCer.setToolTip("")
        self.showCer.setWhatsThis("")
        self.showCer.setAccessibleName("")
        self.showCer.setAccessibleDescription("")
        self.showCer.setAutoFillBackground(False)
        self.showCer.setStyleSheet(
            "background-image: url(:/cer/input/nidhi.jpg)")
        self.showCer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.showCer.setFrameShadow(QtWidgets.QFrame.Plain)
        self.showCer.setMidLineWidth(0)
        self.showCer.setText("")
        self.showCer.setTextFormat(QtCore.Qt.PlainText)
        self.showCer.setPixmap(QtGui.QPixmap(":/cer/input/nidhi.jpg"))
        self.showCer.setScaledContents(True)
        self.showCer.setAlignment(QtCore.Qt.AlignCenter)
        self.showCer.setOpenExternalLinks(False)
        self.showCer.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.showCer.setObjectName("showCer")
        self.tabWidget.addTab(self.Open, "")
        self.Certi = QtWidgets.QWidget()
        self.Certi.setObjectName("Certi")
        self.sditCer = QtWidgets.QLabel(self.Certi)
        self.sditCer.setGeometry(QtCore.QRect(20, 10, 740, 311))
        self.sditCer.setMaximumSize(QtCore.QSize(740, 311))
        self.sditCer.setText("")
        self.sditCer.setPixmap(QtGui.QPixmap(":/cer/input/nidhi.jpg"))
        self.sditCer.setScaledContents(True)
        self.sditCer.setAlignment(QtCore.Qt.AlignCenter)
        self.sditCer.setWordWrap(False)
        self.sditCer.setObjectName("sditCer")
        self.fontComboBox = QtWidgets.QFontComboBox(self.Certi)
        self.fontComboBox.setGeometry(QtCore.QRect(90, 420, 201, 31))
        self.fontComboBox.setObjectName("fontComboBox")
        self.spinBox = QtWidgets.QSpinBox(self.Certi)
        self.spinBox.setGeometry(QtCore.QRect(310, 420, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.spinBox.setFont(font)
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setMaximum(500)
        self.spinBox.setSingleStep(5)
        self.spinBox.setProperty("value", 50)
        self.spinBox.setObjectName("spinBox")
        self.ySlider = QtWidgets.QSlider(self.Certi)
        self.ySlider.setGeometry(QtCore.QRect(140, 370, 411, 22))
        self.ySlider.setAutoFillBackground(False)
        self.ySlider.setMinimum(-600)
        self.ySlider.setMaximum(600)
        self.ySlider.setSingleStep(10)
        self.ySlider.setOrientation(QtCore.Qt.Horizontal)
        self.ySlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.ySlider.setObjectName("ySlider")
        self.xOffset = QtWidgets.QLabel(self.Certi)
        self.xOffset.setGeometry(QtCore.QRect(30, 340, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.xOffset.setFont(font)
        self.xOffset.setAlignment(QtCore.Qt.AlignCenter)
        self.xOffset.setObjectName("xOffset")
        self.yOffset = QtWidgets.QLabel(self.Certi)
        self.yOffset.setGeometry(QtCore.QRect(30, 370, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.yOffset.setFont(font)
        self.yOffset.setAlignment(QtCore.Qt.AlignCenter)
        self.yOffset.setObjectName("yOffset")
        self.xSlider = QtWidgets.QSlider(self.Certi)
        self.xSlider.setGeometry(QtCore.QRect(140, 340, 411, 22))
        self.xSlider.setAutoFillBackground(False)
        self.xSlider.setMinimum(-600)
        self.xSlider.setMaximum(600)
        self.xSlider.setSingleStep(10)
        self.xSlider.setOrientation(QtCore.Qt.Horizontal)
        self.xSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.xSlider.setObjectName("xSlider")
        self.showBtn = QtWidgets.QPushButton(self.Certi)
        self.showBtn.setGeometry(QtCore.QRect(630, 350, 131, 41))
        self.showBtn.setObjectName("showBtn")
        self.confirmBtn = QtWidgets.QPushButton(self.Certi)
        self.confirmBtn.setGeometry(QtCore.QRect(620, 410, 151, 51))
        self.confirmBtn.setObjectName("confirmBtn")
        self.colorBox = QtWidgets.QComboBox(self.Certi)
        self.colorBox.setGeometry(QtCore.QRect(410, 420, 141, 31))
        self.colorBox.setObjectName("colorBox")
        self.colorBox.addItem("")
        self.colorBox.addItem("")
        self.colorBox.addItem("")
        self.tabWidget.addTab(self.Certi, "")
        self.SendMail = QtWidgets.QWidget()
        self.SendMail.setObjectName("SendMail")
        self.inpEmail = QtWidgets.QLineEdit(self.SendMail)
        self.inpEmail.setGeometry(QtCore.QRect(190, 20, 541, 31))
        self.inpEmail.setObjectName("inpEmail")
        self.inpPassword = QtWidgets.QLineEdit(self.SendMail)
        self.inpPassword.setGeometry(QtCore.QRect(190, 70, 541, 31))
        self.inpPassword.setObjectName("inpPassword")
        self.inpSub = QtWidgets.QTextEdit(self.SendMail)
        self.inpSub.setGeometry(QtCore.QRect(190, 130, 541, 91))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.inpSub.setFont(font)
        self.inpSub.setObjectName("inpSub")
        self.inpBody = QtWidgets.QTextEdit(self.SendMail)
        self.inpBody.setGeometry(QtCore.QRect(190, 240, 541, 211))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.inpBody.setFont(font)
        self.inpBody.setObjectName("inpBody")
        self.email = QtWidgets.QLabel(self.SendMail)
        self.email.setGeometry(QtCore.QRect(40, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.email.setFont(font)
        self.email.setObjectName("email")
        self.password = QtWidgets.QLabel(self.SendMail)
        self.password.setGeometry(QtCore.QRect(40, 70, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.sub = QtWidgets.QLabel(self.SendMail)
        self.sub.setGeometry(QtCore.QRect(40, 140, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.sub.setFont(font)
        self.sub.setObjectName("sub")
        self.body = QtWidgets.QLabel(self.SendMail)
        self.body.setGeometry(QtCore.QRect(40, 250, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.body.setFont(font)
        self.body.setObjectName("body")
        self.tabWidget.addTab(self.SendMail, "Send Mail")
        self.Final = QtWidgets.QWidget()
        self.Final.setObjectName("Final")
        self.consoleLog = QtWidgets.QTextBrowser(self.Final)
        self.consoleLog.setGeometry(QtCore.QRect(20, 40, 751, 371))
        self.consoleLog.setStyleSheet("")
        self.consoleLog.setObjectName("consoleLog")
        self.tabWidget.addTab(self.Final, "")
        self.Prev = QtWidgets.QPushButton(self.centralwidget)
        self.Prev.setGeometry(QtCore.QRect(20, 540, 121, 28))
        self.Prev.setObjectName("Prev")
        self.Next = QtWidgets.QPushButton(self.centralwidget)
        self.Next.setGeometry(QtCore.QRect(660, 540, 121, 28))
        self.Next.setObjectName("Next")
        self.guideBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.guideBox.setGeometry(QtCore.QRect(160, 530, 471, 51))
        self.guideBox.setObjectName("guideBox")
        AutoMail.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AutoMail)
        self.statusbar.setObjectName("statusbar")
        AutoMail.setStatusBar(self.statusbar)

        self.retranslateUi(AutoMail)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AutoMail)

    def retranslateUi(self, AutoMail):
        _translate = QtCore.QCoreApplication.translate
        AutoMail.setWindowTitle(_translate("AutoMail", "MainWindow"))
        self.openCsv.setText(_translate("AutoMail", "Open CSV : "))
        self.browse.setText(_translate("AutoMail", "Browse"))
        self.name.setText(_translate("AutoMail", "Name column :"))
        self.mail.setText(_translate("AutoMail", "Email column :"))
        self.openCer.setText(_translate("AutoMail", "Certificate : "))
        self.browse_2.setText(_translate("AutoMail", "Browse"))
        self.loadData.setText(_translate("AutoMail", "Load Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.Open), _translate("AutoMail", "Open Files"))
        self.xOffset.setText(_translate("AutoMail", "X offset "))
        self.yOffset.setText(_translate("AutoMail", "Y offset "))
        self.showBtn.setText(_translate("AutoMail", "Show"))
        self.confirmBtn.setText(_translate("AutoMail", "Confirm"))
        self.colorBox.setItemText(0, _translate("AutoMail", "Black"))
        self.colorBox.setItemText(1, _translate("AutoMail", "Red"))
        self.colorBox.setItemText(2, _translate("AutoMail", "Blue"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.Certi), _translate("AutoMail", "Certificate"))
        self.email.setText(_translate("AutoMail", "Your Email : "))
        self.password.setText(_translate("AutoMail", "App Password :"))
        self.sub.setText(_translate("AutoMail", "Subject : "))
        self.body.setText(_translate("AutoMail", "Body :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.Final), _translate("AutoMail", "Final "))
        self.Prev.setText(_translate("AutoMail", "Prev"))
        self.Next.setText(_translate("AutoMail", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AutoMail = QtWidgets.QMainWindow()
    ui = Ui_AutoMail()
    ui.setupUi(AutoMail)
    AutoMail.show()
    sys.exit(app.exec_())
